trigger: none   # run manually for infra

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'Abinaya-Azure'
  resourceGroup: 'springboot-rg-dev'

stages:
  - stage: Infra
    displayName: 'Deploy AKS + ACR + Key Vault + Log Analytics'
    jobs:
      - job: DeployInfra
        displayName: 'Bicep Infra Deployment'
        steps:

          - checkout: self

          - task: AzureCLI@2
            displayName: 'Deploy infra using Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Starting infra deployment..."
                
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file infra/main.bicep \
                  --parameters @infra/main.dev.parameters.json