apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-kv
  namespace: dev
spec:
  provider: azure
  parameters:
    clientID: "c3953b97-6830-4cc5-bdaa-4be272a51f26"
    keyvaultName: "pay-kv-dev-12345"
    tenantId: "1aae31e0-8eaf-4e9e-9938-467c5739beca"
    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret