apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-kv
  namespace: dev
spec:
  provider: azure
  parameters:
    clientID: "c3953b97-6830-4cc5-bdaa-4be272a51f26"
    keyvaultName: "pay-kv-dev-12345"
    tenantId: "1aae31e0-8eaf-4e9e-9938-467c5739beca"
    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: db-url
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: redis-host
          objectType: secret
        - |
          objectName: redis-port
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: redis-ssl
          objectType: secret
        - |
          objectName: kafka-bootstrap-servers
          objectType: secret
        - |
          objectName: kafka-security-protocol
          objectType: secret
        - |
          objectName: kafka-sasl-mechanism
          objectType: secret
        - |
          objectName: kafka-sasl-jaas-config
          objectType: secret
        - |
          objectName: kafka-topic-payment-created
          objectType: secret
        - |
          objectName: kafka-consumer-group
          objectType: secret
        - |
          objectName: kafka-auto-offset-reset
          objectType: secret